/*******************************************************************************
 * ARICPP - ARI interface for C++
 * Copyright (C) 2017 Daniele Pallastrelli
 *
 * This file is part of aricpp.
 * For more information, see http://github.com/daniele77/aricpp
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 ******************************************************************************/


#include <boost/program_options.hpp>
#include <string>
#include <thread>
#include "../aricpp/client.h"
#include "../aricpp/urlencode.h"

using namespace std;
using namespace aricpp;

int main( int argc, char* argv[] )
{
    try
    {
        string host = "localhost";
        string port = "8088";
        string username = "asterisk";
        string password = "asterisk";
        string application = "attendant";
        string to = "291";
        string from = "290";

        namespace po = boost::program_options;
        po::options_description desc("Allowed options");
        desc.add_options()
            ("help,h", "produce help message")
            ("version,V", "print version string")

            ("host,H", po::value(&host), "ip address of the ARI server [localhost]")
            ("port,P", po::value(&port), "port of the ARI server [8088]")
            ("username,u", po::value(&username), "username of the ARI account on the server [asterisk]")
            ("password,p", po::value(&password), "password of the ARI account on the server [asterisk]")
            ("application,a", po::value(&application), "stasis application to use [attendant]")
            ("from,f", po::value(&from), "source extension [290]")
            ("to,t", po::value(&to), "destination extension [291]")
        ;

        po::variables_map vm;
        po::store(po::parse_command_line(argc, argv, desc), vm);
        po::notify(vm);

        if (vm.count("help"))
        {
            std::cout << desc << "\n";
            return 0;
        }

        if (vm.count("version"))
        {
            cout << "This is chat application v. 1.0, part of aricpp library\n";
            return 0;
        }

        boost::asio::io_service ios;

        Client client( ios, host, port, username, password, application );
        client.Connect( [&](boost::system::error_code ){

            client.OnEvent( "TextMessageReceived", [&](const Event& e){
                auto from = e.at("message").at("from");
                auto to = e.at("message").at("to");
                auto msg = e.at("message").at("body");

                cout << "> Message from: " << from << " (for: " << to << "):\n";
                cout << msg << "\n\n";
            });
        });

        auto inputReader = [&]()
        {
            string msg;
            while (true)
            {
                cout << "> Enter you message (quit to exit):\n";
                getline( std::cin, msg );
                if (msg == "exit" || msg == "quit") break;
                if (msg.empty()) continue;
                cout << "Sending " << msg << '\n';
                msg = UrlEncode(msg);
                auto url = "/ari/endpoints/sendMessage?to=sip:"+to+"&from=sip:"+from+"&body="+msg;
                auto sendRequest =
                    [&client,url]()
                    {
                        client.RawCmd("PUT", url, [](auto,auto,auto,auto){});
                    };
                ios.post( sendRequest );
            }
            cout << "Exiting application\n";
            ios.stop();
        };
        thread readerThread( inputReader );

        ios.run();

        readerThread.join();

    }
    catch ( const exception& e )
    {
        cerr << "Exception in app: " << e.what() << ". Aborting\n";
        return -1;
    }
    return 0;
}
